name: 'Consonant vowel ratio'
author: 'Mohini Pathak'
description: 'Custom GH action with TypeScript'

inputs:
  name:
    description: 'Name to greet'
    required: false
    default: 'Demoooo'

runs:
  using: 'node16'
  main: 'dist/index.js'